name: Print Name

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
                required: true
                description: 'Enter name'
                type: string
                default: "NAME"

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        # run: echo "MY_${{ inputs.name }}_SECRET"
        env:
          MY_NAME: ${{ secrets.MY_NAME_SECRET }}
        run: python print_name.py
        working-directory: ./folder/folder_second

      - name: Print Variable
        run: |
          # Print the value of the variable
          echo "Variable Value: $VARIABLE_NAME"
        
