name: Print Name

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        env:
          MY_NAME: ${{ secrets.MY_NAME_SECRET }}
        run: python ./s/test/print_name.py
