name: Print Name

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        required: false
        description: 'Enter name'
        type: string
        default: "NAME"
      envName:
        description: 'Specify the environment name.'
        required: true
        type: choice
        options:
          - dev
          - tst
          - prd

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Run Python Script
      #   # run: echo "MY_${{ inputs.name }}_SECRET"
      #   env:
      #     MY_NAME: ${{ secrets.MY_NAME_SECRET }}
      #   run: python print_name.py
      #   working-directory: ./folder/folder_second

      # - name: Print Variable
      #   uses: ./.github/variables
      #   run: |
      #     # Print the value of the variable
      #     echo "Variable Value: $VARIABLE_NAME"
      # - name: Retrive dev cred
      #   run: |
      #     ENVIRONMENT="${{github.event.inputs.envName}}_Name"
      #     ADMIN_USERNAME="${{ secrets[${ENVIRONMENT}] }}"

      - name: Print dev secret
        # run: echo "devName:$ADMIN_USERNAME"
        run: echo "${{ secrets[format('{0}_Name', github.event.inputs.envName)] }}"
